# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=0.2
group=com.mars.cookedcarrots
java_version=17
deimos_version=2.2
# Common
mod_name=Cooked Carrots
mod_author=Mars
mod_id=cookedcarrots
license=MIT
homepage=https://modrinth.com/mod/cooked-carrots
description=Just like normal carrots, but you eat them faster
minecraft_version=1.20.2
modmenu_version=8.0.1
minecraft_version_range=[1.20.2, 1.21)
# Fabric
fabric_version=0.91.6+1.20.2
fabric_loader_version=0.16.9
# Forge
forge_version=48.0.49
forge_loader_version_range=[48,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
